@echo off
cd /d "C:\Users\Simon\OneDrive\Desktop\Trea Demo"
echo Adding all changes to git...
git add .
echo Committing changes...
git commit -m "Update to V4: Added current shift filtering and event archiving functionality"
echo Verifying remote URL...
git remote -v
echo Pushing to V4 repository...
git push origin main
echo Backup to V4 repository completed!
pause